kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
annotations:
  storageclass.beta.kubernetes.io/is-default-class: "true"
metadata:
  name: standard
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  encrypted: "true"
